pipeline {
    agent any

    tools {
        nodejs "Node 20"
    }

    environment {
        GITHUB_TOKEN = credentials('gitHubToken')
        GITHUB_REPOSITORY = 'JuankCadavid/testing_devops'
    }

    stages {

        stage('Print branch name') {
            steps {
                echo "Branch name is: ${env.GIT_BRANCH}"
            }
        }

        stage('Cloning Git') {
            steps {
                git branch: 'master', url: 'https://github.com/JuankCadavid/testing_devops'
            }
        }

        stage('Startup') {
            steps {
                dir('devops') {
                    sh 'npm install'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    try {
                        dir('devops') {
                            sh 'npm test'
                        }
                    } catch (Exception e) {
                        env.BUILD_EXCEPTION = "Stage: ${env.STAGE_NAME}, Error: ${e.message}"
                        env.FAILED_STAGE = "Stage: ${env.STAGE_NAME}"
                        e.printStackTrace() // print the stack trace
                        throw e // rethrow the exception to fail the build
                    }
                }
            }
        }

        stage('Linting') {
            steps {
                script {
                    try {
                        dir('devops') {
                            sh 'npm run lint || exit 1'
                        }
                    } catch (Exception e) {
                        env.BUILD_EXCEPTION = "Stage: ${env.STAGE_NAME}, Error: ${e.message}"
                        env.FAILED_STAGE = "Stage: ${env.STAGE_NAME}"
                        e.printStackTrace() // print the stack trace
                        throw e // rethrow the exception to fail the build
                    }
                }
            }
        }

        stage('Disable branch protection') {

            steps {
                 script {
                    def disableProtection = [
                        required_status_checks: null,
                        enforce_admins: false,
                        required_pull_request_reviews: null,
                        restrictions: null
                    ]
                    httpRequest(
                        url: "https://api.github.com/repos/${GITHUB_REPOSITORY}/branches/master/protection",
                        httpMode: 'DELETE',
                        contentType: 'APPLICATION_JSON',
                        customHeaders: [
                            [name: 'Authorization', value: "token ${GITHUB_TOKEN}"],
                            [name: 'Accept', value: 'application/vnd.github.luke-cage-preview+json']
                        ],
                        validResponseCodes: '204,404'
                    )
                }
            }
        }

        stage('Release') {
            steps {
            withCredentials([string(credentialsId: 'gitHubToken', variable: 'GITHUB_TOKEN')]) {
                dir('devops') {
                sh 'npx semantic-release'
                }
            }
            }
        }

        stage('Re-enable branch protection') {

            steps {
                 script {
                    def protectionConfig = [
                        required_status_checks: [
                            strict: true,
                            contexts: []
                        ],
                        enforce_admins: true,
                        required_pull_request_reviews: [
                            dismissal_restrictions: [:],
                            dismiss_stale_reviews: true,
                            require_code_owner_reviews: true,
                            required_approving_review_count: 1
                        ],
                        restrictions: null
                    ]
                    httpRequest(
                        url: "https://api.github.com/repos/${GITHUB_REPOSITORY}/branches/master/protection",
                        httpMode: 'PUT',
                        contentType: 'APPLICATION_JSON',
                        requestBody: groovy.json.JsonOutput.toJson(protectionConfig),
                        customHeaders: [
                            [name: 'Authorization', value: "token ${GITHUB_TOKEN}"],
                            [name: 'Accept', value: 'application/vnd.github.luke-cage-preview+json']
                        ]
                    )
                }
            }
        }
    }
}